INTERVAL = 5

CODE_SUCCESS = 0
TAG_LAST_PRICE = 'last'
TAG_INST_ID = 'instId'

ABOVE_TEN_PERCENT = 3
ABOVE_FIVE_PERCENT = 2
ABOVE = 1
EQUAL = 0
BELOW = -1
BELOW_FIVE_PERCENT = -2
BELOW_TEN_PERCENT = -3
